name:                elm-websocket
version:             1.1
synopsis:            Generate ELM code from a Wai websocket application.
description:         Please see README.md
homepage:            http://github.com/rhyskeepence/elm-websocket
license:             BSD3
license-file:        LICENSE
author:              Rhys Keepence
maintainer:          rhyskeepence@gmail.com
copyright:           2017 Rhys Keepence
category:            Web
build-type:          Simple
ghc-options:         -Wall

dependencies:
- aeson
- base
- mtl
- text
- wai

library:
  source-dirs: src
  exposed-modules:     
  - Elm.WebSocket
  - Elm.Export
  dependencies:       
  - bytestring
  - concurrent-extra
  - containers
  - directory
  - formatting
  - lens
  - stm
  - time
  - wai-websockets
  - websockets
  - wl-pprint-text

tests:
  spec:
    source-dirs:      
    - test
    main: Spec.hs
    dependencies:      
    - concurrent-extra
    - elm-websocket
    - hspec
    - http-types
    - network
    - websockets
    - warp
    ghc-options: 
    - -threaded 
    - -rtsopts 
    - -with-rtsopts=-N

executable elm-websocket-example:
  hs-source-dirs:      
  - example/server/src
  - example/server/shared
  main: Main.hs
  ghc-options:
  - -threaded 
  - -rtsopts 
  - -with-rtsopts=-N
  build-depends: 
  - concurrent-extra
  - elm-websocket
  - http-types
  - scotty
  - wai-middleware-static
  - warp

executable elm-websocket-code-generator:
  hs-source-dirs:      example/code-generator, example/server/shared
  main-is:             Main.hs
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N -Wall
  build-depends:
  - concurrent-extra
  - elm-websocket
  - http-types
  - scotty
  - wai-middleware-static
  - warp

